require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Rails:
  Enabled: true

Documentation:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals
  SupportedStyles:
    - always
    - conditionals

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/MultipleExpectations:
  Max: 2
