language: ruby
cache: bundler
env:
  - DB_USER=postgres
  - DB_PASSWORD=
services:
  - postgresql
postgres:
  adapter: postgresql
  database: phobrary_test
  username: postgres
before_script:
  - "psql -c 'create database phobrary_test;' -U postgres"
  - "bundle exec rails db:migrate"
rvm:
  - 2.5.1
  - ruby-head
install:
  - gem install bundler
  - bundle install
script:
  - bundle exec rspec
