development:
  adapter: redis
  channel_prefix: phobrary_development

test:
  adapter: test
  channel_prefix: phobrary_test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: phobrary_production
