default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>
  timeout: 5000
  connect_timeout: 1
  variables:
    statement_timeout: 1500 # ms

development:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || "phobrary_development" %>
  username: <%= ENV['DB_USER'] || "phobrary" %>
  password: <%= ENV['DB_PASSWORD'] || "phobrary123" %>
  host: <%= ENV['DB_HOST'] || "localhost" %>
  port: <%= ENV['DB_PORT'] || 5432 %>

test:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || "phobrary_test" %>
  username: <%= ENV['DB_USER'] || "phobrary" %>
  password: <%= ENV['DB_PASSWORD'] || "phobrary123" %>
  host: <%= ENV['DB_HOST'] || "localhost" %>
  port: <%= ENV['DB_PORT'] || 5432 %>

production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
